Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
multi_exps1_reades = experiment_hadamard.multiRead(
    save_location=".",
    summoner_name="qurrent.hadamard_test.001",
)
------------------


[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[16][39m[32m, line 1[39m
[32m----> [39m[32m1[39m multi_exps1_reades = [43mexperiment_hadamard[49m[43m.[49m[43mmultiRead[49m[43m([49m
[32m      2[39m [43m    [49m[43msave_location[49m[43m=[49m[33;43m"[39;49m[33;43m.[39;49m[33;43m"[39;49m[43m,[49m
[32m      3[39m [43m    [49m[43msummoner_name[49m[43m=[49m[33;43m"[39;49m[33;43mqurrent.hadamard_test.001[39;49m[33;43m"[39;49m[43m,[49m
[32m      4[39m [43m)[49m

[36mFile [39m[32m/usr/local/lib/python3.12/site-packages/qurry/qurrium/qurrium.py:823[39m, in [36mQurriumPrototype.multiRead[39m[34m(self, summoner_name, save_location, reload, read_from_tarfile)[39m
[32m    818[39m [38;5;28;01melif[39;00m [38;5;28mlen[39m(filtered_summoner_id_names) > [32m1[39m:
[32m    819[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[32m    820[39m         [33mf[39m[33m"[39m[33mMultiple multimanager found for [39m[33m'[39m[38;5;132;01m{[39;00msummoner_name[38;5;132;01m}[39;00m[33m'[39m[33m: [39m[38;5;132;01m{[39;00mfiltered_summoner_id_names[38;5;132;01m}[39;00m[33m.[39m[33m"[39m
[32m    821[39m     )
[32m--> [39m[32m823[39m current_multimanager = [43mMultiManager[49m[43m.[49m[43mread[49m[43m([49m
[32m    824[39m [43m    [49m[43msummoner_name[49m[43m=[49m[43msummoner_name[49m[43m,[49m
[32m    825[39m [43m    [49m[43mexperiment_instance[49m[43m=[49m[38;5;28;43mself[39;49m[43m.[49m[43mexperiment_instance[49m[43m,[49m
[32m    826[39m [43m    [49m[43msave_location[49m[43m=[49m[43msave_location[49m[43m,[49m
[32m    827[39m [43m    [49m[43mis_read_or_retrieve[49m[43m=[49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[32m    828[39m [43m    [49m[43mread_from_tarfile[49m[43m=[49m[43mread_from_tarfile[49m[43m,[49m
[32m    829[39m [43m[49m[43m)[49m
[32m    830[39m [38;5;28mself[39m.multimanagers[current_multimanager.summoner_id] = current_multimanager
[32m    832[39m [38;5;28;01mreturn[39;00m current_multimanager.multicommons.summoner_id

[36mFile [39m[32m/usr/local/lib/python3.12/site-packages/qurry/qurrium/multimanager/multimanager.py:466[39m, in [36mMultiManager.read[39m[34m(cls, summoner_name, experiment_instance, save_location, is_read_or_retrieve, read_from_tarfile, encoding)[39m
[32m    442[39m [38;5;129m@classmethod[39m
[32m    443[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mread[39m(
[32m    444[39m     [38;5;28mcls[39m,
[32m   (...)[39m[32m    450[39m     encoding: [38;5;28mstr[39m = [33m"[39m[33mutf-8[39m[33m"[39m,
[32m    451[39m ) -> [33m"[39m[33mMultiManager[39m[33m"[39m:
[32m    452[39m [38;5;250m    [39m[33;03m"""Read the multi-experiment.[39;00m
[32m    453[39m 
[32m    454[39m [33;03m    Args:[39;00m
[32m   (...)[39m[32m    464[39m [33;03m        MultiManager: The container of experiments and multi-experiment.[39;00m
[32m    465[39m [33;03m    """[39;00m
[32m--> [39m[32m466[39m     naming_complex = [43mnaming[49m[43m([49m
[32m    467[39m [43m        [49m[43mis_read[49m[43m=[49m[43mis_read_or_retrieve[49m[43m,[49m
[32m    468[39m [43m        [49m[43mexps_name[49m[43m=[49m[43msummoner_name[49m[43m,[49m
[32m    469[39m [43m        [49m[43msave_location[49m[43m=[49m[43msave_location[49m[43m,[49m
[32m    470[39m [43m    [49m[43m)[49m
[32m    471[39m     gitignore = GitSyncControl()
[32m    472[39m     gitignore.read(naming_complex.export_location)

[36mFile [39m[32m/usr/local/lib/python3.12/site-packages/qurry/qurrium/utils/iocontrol.py:82[39m, in [36mnaming[39m[34m(is_read, exps_name, save_location, short_name, without_serial, rjust_len, index_rename)[39m
[32m     80[39m     tar_location = save_location / tar_name
[32m     81[39m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (export_location.exists() [38;5;129;01mor[39;00m tar_location.exists()):
[32m---> [39m[32m82[39m         [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m(
[32m     83[39m             [33mf[39m[33m"[39m[33mSuch exportation data [39m[33m'[39m[38;5;132;01m{[39;00mimmutable_name[38;5;132;01m}[39;00m[33m'[39m[33m or [39m[33m"[39m
[32m     84[39m             + [33mf[39m[33m"[39m[33m'[39m[38;5;132;01m{[39;00mtar_name[38;5;132;01m}[39;00m[33m'[39m[33m not found at [39m[33m'[39m[38;5;132;01m{[39;00msave_location[38;5;132;01m}[39;00m[33m'[39m[33m, [39m[33m"[39m
[32m     85[39m             + [33m"[39m[33m'[39m[33mexports name[39m[33m'[39m[33m may be wrong or not in this folder.[39m[33m"[39m
[32m     86[39m         )
[32m     87[39m     [38;5;28mprint[39m([33mf[39m[33m"[39m[33m| Retrieve [39m[38;5;132;01m{[39;00mimmutable_name[38;5;132;01m}[39;00m[33m...[39m[38;5;130;01m\n[39;00m[33m"[39m + [33mf[39m[33m"[39m[33m| at: [39m[38;5;132;01m{[39;00mexport_location[38;5;132;01m}[39;00m[33m"[39m)
[32m     88[39m [38;5;28;01melif[39;00m without_serial:

[31mFileNotFoundError[39m: Such exportation data 'qurrent.hadamard_test.001' or 'qurrent.hadamard_test.001.qurry.tar.xz' not found at '.', 'exports name' may be wrong or not in this folder.

